'use strict';

// Replace with your unique name
exports.appName = 'Default Application';

// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
var gcmServerApiKey = process.env.GCM_SERVER_API_KEY;
exports.gcmServerApiKey = gcmServerApiKey || 'Your-server-api-key';

// You may want to use your own credentials here
// exports.apnsCertData = readCredentialsFile('apns_cert_dev.pem');
// exports.apnsKeyData = readCredentialsFile('apns_key_dev.pem');

//--- Helper functions ---

function readCredentialsFile(name) {
  return fs.readFileSync(
    path.resolve(__dirname, 'credentials', name),
    'UTF-8'
  );
}
